// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsW2K-BtGxmDXKiItNKXA4pDwq5efkWNU',
    appId: '1:292253035892:web:56cd5d82b8fc29e0769021',
    messagingSenderId: '292253035892',
    projectId: 'geotagging-b9974',
    authDomain: 'geotagging-b9974.firebaseapp.com',
    storageBucket: 'geotagging-b9974.appspot.com',
    measurementId: 'G-HYV9NMG56D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZRjKWGmN0IorJFP-lnuuyGM2tOW5gm8',
    appId: '1:292253035892:android:e3517b617c8376ed769021',
    messagingSenderId: '292253035892',
    projectId: 'geotagging-b9974',
    storageBucket: 'geotagging-b9974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHO2D7XDzx_rXXK2AqjO7NgAYaklJzTrY',
    appId: '1:292253035892:ios:e6ea14f7b05727e7769021',
    messagingSenderId: '292253035892',
    projectId: 'geotagging-b9974',
    storageBucket: 'geotagging-b9974.appspot.com',
    iosBundleId: 'com.example.nstw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHO2D7XDzx_rXXK2AqjO7NgAYaklJzTrY',
    appId: '1:292253035892:ios:db74186231866ee6769021',
    messagingSenderId: '292253035892',
    projectId: 'geotagging-b9974',
    storageBucket: 'geotagging-b9974.appspot.com',
    iosBundleId: 'com.example.nstw.RunnerTests',
  );
}
